### ISSUE TITLE
Window flash

### ISSUE THREAD

**Issue by DustyLoon** [MScholtes/TechNet-Gallery#1]
This script is awesome, you are very generous for sharing it.

I have a powershell script that is supposed to do a few things in the background and then exit. I have "compiled" the a script using the following flags:

-inputFile my.ps1 
-outputFile my.exe 
-noConsole
-iconFile my.ico 
-title 'Fancy Title' 
-company 'Your name here' 
-copyright '2020' 
-version '1.0' 
-noOutput  
-noError  
-noVisualStyles

When the exe file is lauched, for a brief moment a console window appears and disappears. I thought that the -noConsole flag meant it would not open up a console window, but it seems like that's what it's doing. Something also briefly flashes in taskbar.

The first line of my script has the following:

$Global:progresspreference='SilentlyContinue'

So presumably it's not the script trying to open anything.

I'd appreciate any suggestions on how to make the exe truly run in the background at launch.

**Comment by MScholtes** [comment]
Hello DustyLoon,

I've done a few tries and I can't recreate the behavior.

How do you start the program? Have you installed a debugger or something similar?

Greetings

Markus

**Comment by DustyLoon** [comment]
Thanks for the reply! I am launching it by double-clicking on the exe file that was generated. For just a brief moment (less than a second) and window appears and disappears along with an blank icon appearing and disappearing (you only see the underline where the icon would be) in the taskbar. I can try to record a video of the screen if that helps.

**Comment by MScholtes** [comment]
Hello DustyLoon,

what is your script doing?

Greetings

Markus

**Comment by DustyLoon** [comment]
It gathers a bunch of asset information, mostly through the use of Get-WmiObject, but Get-NetIPAddress and Get-CimInstance are also used. I also directly use wmic bios get smbiosbiosversion and netsh mbn sh int to poll information. Lastly I obtain position information using System.Device.Location.GeoCoordinateWatcher

The flash is so quick it's really hardly noticeable, I won't have any issues using the .exe moving forward, I just know eventually one of my users will call thinking there is a virus (because anything that flashes quickly must be a virus right?).

**Comment by MScholtes** [comment]
Hello DustyLoon,

everything is clear now: **netsh** and **wmic** start their own command line windows. Try the command **netsh help** in a PowerShell console and see the effect.

You have to use something like
**Start-Process -WindowsStyle Hidden "netsh help"**
when calling those tools to hide their console windows.

Greetings

Markus

**Comment by DustyLoon** [comment]
Thank you so much! I can't thank you enough for making your program open for everyone to use and the fantastic support here.
