### ISSUE TITLE
"FALSE" value being removed

### ISSUE THREAD

**Issue by memphisraynz** [MScholtes/TechNet-Gallery#16]
Properties with the value of FALSE are having the value stripped.
Have multiple columns where the value is false, after transposing the value is now null.

**Comment by MScholtes** [comment]
Hello @memphisraynz,

are you writing about the script _Transpose-Object_?

Greetings

Markus

**Comment by memphisraynz** [comment]
Yes it is.
I did find a solution. Looks like the If statement was returning false.
Found that if the If statement on line 70 is changed to 'if (-not [string]::IsNullOrEmpty($InputObject.($_)))' it works

**Comment by MScholtes** [comment]
Hello @memphisraynz,

I released a new version of _Transpose-Object_ today. My solution differs slightly from yours as I want to keep an empty string preserved. Hope that's fine for you.

Greetings

Markus

**Comment by MScholtes** [comment]
Solution provided
