### ISSUE TITLE
PS2EXE-GUI: Make the example for determining the executable's own full path / directory path more robust

### ISSUE THREAD

**Issue by mklement0** [MScholtes/TechNet-Gallery#17]
First things first: thank you and Ingo for a great tool.

When you call an executable from `cmd.exe`, `[Environment]::GetCommandLineArgs()[0])` reports the executable _as specified_, not necessarily by its _full path_ (the latter only happens when calling from PowerShell).

Therefore, a `Convert-Path` call is needed for robustness:

```powershell
$ScriptPath = Split-Path -Parent (Convert-Path -LiteralPath ([Environment]::GetCommandLineArgs()[0]))
```

**Comment by MScholtes** [comment]
Hello @mklement0,

thank you for your useful advice.

When I saw it I noticed that I did not update the readme page like I did with the "module version" of **PS2EXE** (https://github.com/MScholtes/PS2EXE): _[Environment]::GetCommandLineArgs()[0]_ might return the executable name without path!

I updated the comment for this: https://github.com/MScholtes/TechNet-Gallery/tree/master/PS2EXE-GUI#script-variables

Greetings

Markus

**Comment by mklement0** [comment]
Thanks for updating, Markus.

While it helps, my concern is that you're not obtaining a _full_ (absolute) path, which is what `$MyInvocation.MyCommand.Definition` returns when running directly as a `.ps1`.

Also note that in v3+ the latter can be replaced with `$PSCommandPath`, and the _directory_ has its own automatic variable, `$PSScriptRoot` - and these variables are only defined when running as a `.ps1` file.

Therefore, I suggest showing the following in the read-me files:

```powershell
$scriptPath = 
  if ($PSScriptRoot) { # running as .ps1 script
    $PSScriptRoot 
  } else {             # running as .exe 
    Split-Path -Parent (Convert-Path -LiteralPath ([System.Environment]::GetCommandLineArgs()[0]))
  }
```
