### ISSUE TITLE
Seems to be broken with Windows 11 23H2

### ISSUE THREAD

**Issue by SuperflyJon** [MScholtes/TechNet-Gallery#18]
I get errors like:
`The type initializer for 'VirtualDesktop.DesktopManager' threw an exception`

**Comment by MScholtes** [comment]
Hello @SuperflyJon,

I updated VirtualDesktop to version 2.1.8 today, it should work with this.

Greetings

Markus

**Comment by SuperflyJon** [comment]
Thanks, that’s fixed it!
