### ISSUE TITLE
[PS2EXE] Add -noExtract parameter

### ISSUE THREAD

**Issue by Hope-IT-Works** [MScholtes/TechNet-Gallery#3]
Hello Markus,

i have a feature for ps2exe that is very nice to have.

I've contacted Ingo Karstein, the original author of ps2exe and asked him, how i could remove the -extract feature from the ps2exe-script. He told me it's as simple as removing this else-if from the script:

```
							else if (s.StartsWith("-extract", StringComparison.InvariantCultureIgnoreCase))
							{
								string[] s1 = s.Split(new string[] { ":" }, 2, StringSplitOptions.RemoveEmptyEntries);
								if (s1.Length != 2)
								{
$(if (!$noConsole) {@"
									Console.WriteLine("If you specify the -extract option you need to add a file for extraction in this way\r\n   -extract:\"<filename>\"");
"@ } else {@"
									MessageBox.Show("If you specify the -extract option you need to add a file for extraction in this way\r\n   -extract:\"<filename>\"", System.AppDomain.CurrentDomain.FriendlyName, MessageBoxButtons.OK, MessageBoxIcon.Error);
"@ })
									return 1;
								}
								extractFN = s1[1].Trim(new char[] { '\"' });
							}
```

It would be great if you would add a -noExtract feature for the ps2exe-script.

Thanks in advance and have a nice day,
@Hope-IT-Works

**Comment by MScholtes** [comment]
Hello ChocolateDay | Tobias Meyer,

I am a big fan of free software, so **PS2EXE** itself is free. I am reluctant to make the compilations generated by **PS2EXE** closed source.

There may be situations where this makes sense. Please replace the expression **_s.StartsWith("-extract", StringComparison.InvariantCultureIgnoreCase)_** in _PS2EXE.ps1_ with the expression **_false_** then the parameter _-extract_ is gone for future compilations.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for over 2 weeks
