### ISSUE TITLE
Software issue

### ISSUE THREAD

**Issue by bruce1949** [MScholtes/TechNet-Gallery#5]
Hi Sir,
  Thanks for your great tool that I can convert the script to exe application. I found two errors and need your assistance to find the root of the issue;
1、Write-host,  -ForegroundColor will not work after convert to exe file. for example, after I convert it to exe, the font text is white other that the font color I set.
     
`Write-Host "Hello World" -ForegroundColor Yellow
` 
2、Write-progress, Write-progress will not closed until the application execute all the code.
` Write-Progress  Download Percentage: $($data[0])" -Activity "File Downloading" -ErrorAction SilentlyContinue`
![111](https://user-images.githubusercontent.com/10904633/93464278-83451f80-f91b-11ea-8aae-14827e9a383a.png)
![333](https://user-images.githubusercontent.com/10904633/93464282-850ee300-f91b-11ea-832f-9c0937413d29.png)

I am not sure if we can set the font, background color with your tools. It would be a great if this feature is integrated in this tool.

**Comment by MScholtes** [comment]
Hello Bruce1949,

here are the answers to your requests:

1. I made some tests with **Write-Host** and the parameter **-ForegroundColor**. It's working fine in my envirnment.
What is happening for you when you run your script uncompiled? Or are you using the GUI Version? There is no support for setting colours then because it is really ugly.

2. I do not understand your question, this is the expected behaviour. 
Please close your progress bars with the provided parameter **-Completed** for **Write-Progress** when you've finished your actions.

Greetings

Markus

**Comment by bruce1949** [comment]
Sorry for the delay and it's my fault that I correct in my script. This is really a great tool. BTW, Do you have any plan that upgrade the tool so that end user can't extract it to avoid password leak? Thanks in advance.

**Comment by MScholtes** [comment]
Hello Bruce1949,

I am a big fan of free software, so _PS2EXE_ itself is free. I am reluctant to make the compilations generated by _PS2EXE_ closed source.

There may be situations where this makes sense. Please replace the expression **_s.StartsWith("-extract", StringComparison.InvariantCultureIgnoreCase)_** in _PS2EXE.ps1_ with the expression **_false_** then the parameter -extract is gone for future compilations.

Greetings

Markus

**Comment by bruce1949** [comment]
Really appreciate for your contribution and I will try and feedback later

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: MScholtes <notifications@github.com>
发送时间: Tuesday, October 6, 2020 9:15:50 PM
收件人: MScholtes/TechNet-Gallery <TechNet-Gallery@noreply.github.com>
抄送: bruce1949 <zhang.yao@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [MScholtes/TechNet-Gallery] Software issue (#5)


HelloBruce1949,

I am a big fan of free software, so PS2EXE itself is free. I am reluctant to make the compilations generated by PS2EXE closed source.

There may be situations where this makes sense. Please replace the expression s.StartsWith("-extract", StringComparison.InvariantCultureIgnoreCase) in PS2EXE.ps1 with the expression false then the parameter -extract is gone for future compilations.

Greetings

Markus

―

**Comment by MScholtes** [comment]
Closed since no response for over 3 weeks
