### ISSUE TITLE
Pressing cancel in the GUI while waiting for input continues script

### ISSUE THREAD

**Issue by jc250742** [MScholtes/TechNet-Gallery#6]
I wrote a small script that asks user for input through read-host, if the user enters nothing and leave the input box blank, a default entry is made when OK is clicked, this works great, However when in the GUI cancel is selected the script still proceeds and continues as if the user selected enter. Hitting cancel is not killing the script?

**Comment by MScholtes** [comment]
Hello Johnathan,

I guess you're talking about PS2EXE.

Yes, hitting cancel does not stop the program. I think it would be a too "hefty" reaction to stop the program, it is rather a cancel of the input.

Greetings

Markus

**Comment by jc250742** [comment]
When you say, cancel of the input, what does that mean in Powershell?
If this was in cmd line how would that work? Is there a way for me to detect that cancel was used in my script ?



[cid:image001.jpg@01D6C19B.D9429780]Johnathan Copeland

NCR Corporation
Phone: +1-519-880-7768
Johnathan.Copeland@ncr.com<mailto:Johnathan.Copeland@ncr.com>  |  ncr.com<http://www.ncr.com/>
[cid:image006.png@01D6C19B.D94D1ED0]<https://www.facebook.com/ncrcorp>­  [cid:image007.png@01D6C19B.D94D1ED0] <https://twitter.com/NCRCorporation>    [cid:image008.png@01D6C19B.D94D1ED0] <https://www.linkedin.com/company/ncr-corporation>   [cid:image005.png@01D6C19B.D9429780] <https://www.instagram.com/ncrcorporation/?hl=en>

**Comment by MScholtes** [comment]
Cancel means the same as no input.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for over 3 weeks
