### ISSUE TITLE
Accented characters PS2EXE

### ISSUE THREAD

**Issue by Choum28** [MScholtes/TechNet-Gallery#7]
Hello,

I have a small problem with PS2Exe
When I compile some scripts which contain some accented characters, they will appears as ?
![image](https://user-images.githubusercontent.com/16866992/100856268-7f8d5780-348b-11eb-9a45-cd049859d557.png)

I think it something related to encoding settings inside the PS2EXE scripts but I do not found what to change.

For information in my script such text were inside some texblock (WPF).

**Comment by MScholtes** [comment]
Hello Choum28,

PS2EXE expects the source file in UTF8 encoding (UTF16 works too if source file has a BOM).

You might convert with:
```
Get-Content $SOURCEFILE | Set-Content $SOURCEFILEUTF8 -Encoding UTF8
```

Greetings

Markus

**Comment by Choum28** [comment]
Perfect.

**Comment by MScholtes** [comment]
Closed since no response for over 2 weeks
